"""Precomputed ground truth, and the machinery that keeps it honest.

Ground truth for every task is computed by point-by-point enumeration of its
declared box. That is the whole point of the benchmark -- the answers are facts,
not opinions -- and it costs about 2.8 seconds for the 44-task suite. Paying that
on *every* CLI invocation and every test was pure waste: `soundnessbench tasks`
spent 2.8 s brute-forcing answers it then stripped from its own output.

So the answers are computed once and committed. The obvious danger is a stale
file: a task's relations change, the committed answer does not, and the benchmark
starts grading against a number nobody checked.

Two things prevent that, and the first is the important one:

**Entries are keyed by a hash of the task's own content** -- its domain, guard,
safety and box -- not by its task id. Change any relation and the key changes,
the lookup misses, and the answer is recomputed from scratch. A stale entry is
therefore unreachable rather than merely detectable.

**`soundnessbench verify-ground-truth`** recomputes every answer and compares.
Run in CI, it catches a file that was hand-edited, truncated, or generated by a
different version of the enumerator.

The file is a cache in the strict sense: deleting it changes speed, never
answers.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any

__all__ = [
    "GROUND_TRUTH_PATH",
    "SCHEMA",
    "task_key",
    "load_ground_truth",
    "build_ground_truth",
]

SCHEMA = "soundnessbench/groundtruth/v1"
GROUND_TRUTH_PATH = Path(__file__).resolve().parent / "data" / "ground_truth.json"


def task_key(
    domain: Any,
    guard: Any,
    safety: Any,
    box: Any,
) -> str:
    """A content hash over everything that determines the answer.

    Deliberately excludes the task id, family, difficulty and note: those are
    labels. If two tasks posed literally the same question they would share an
    entry, which is correct. If one task's relations change it gets a new key,
    which is the property that makes staleness impossible.
    """
    payload = json.dumps(
        {"domain": domain, "guard": guard, "safety": safety, "box": box},
        sort_keys=True,
        separators=(",", ":"),
        default=list,
    )
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


_CACHE: dict[str, dict[str, Any]] | None = None


def load_ground_truth(path: Path | None = None) -> dict[str, dict[str, Any]]:
    """Load the committed answers, or return empty if unavailable.

    A missing or unreadable file is not an error -- it costs time, not
    correctness, because every miss falls back to enumeration. A file with the
    wrong schema is ignored for the same reason.
    """
    global _CACHE
    if path is None and _CACHE is not None:
        return _CACHE

    target = path or GROUND_TRUTH_PATH
    entries: dict[str, dict[str, Any]] = {}
    try:
        raw = json.loads(target.read_text(encoding="utf-8"))
        if isinstance(raw, dict) and raw.get("schema") == SCHEMA:
            found = raw.get("entries")
            if isinstance(found, dict):
                entries = {
                    k: v
                    for k, v in found.items()
                    if isinstance(v, dict) and isinstance(v.get("over_acceptance"), int)
                }
    except (OSError, json.JSONDecodeError, TypeError, ValueError):
        entries = {}

    if path is None:
        _CACHE = entries
    return entries


def build_ground_truth(tasks: Any) -> dict[str, Any]:
    """Serialise the answers of an already-computed suite."""
    entries: dict[str, dict[str, Any]] = {}
    for t in tasks:
        entries[task_key(t.domain, t.guard, t.safety, t.box)] = {
            "task_id": t.task_id,
            "over_acceptance": t.over_acceptance,
            "witness": t.witness,
        }
    return {
        "schema": SCHEMA,
        "note": (
            "Precomputed answers, keyed by a content hash of each task's relations. "
            "This is a cache: deleting it changes speed, never answers. Regenerate "
            "with `soundnessbench verify-ground-truth --write`; verify with "
            "`soundnessbench verify-ground-truth`."
        ),
        "n_entries": len(entries),
        "entries": entries,
    }
